modify version

diff --git a/apache-hive-2.1.0-src/bin/hive b/apache-hive-2.1.0-src/bin/hive
--- a/apache-hive-2.1.0-src/bin/hive
+++ b/apache-hive-2.1.0-src/bin/hive
@@ -78,18 +78,18 @@ if [ -f "${HIVE_CONF_DIR}/hive-env.sh" ]; then
   . "${HIVE_CONF_DIR}/hive-env.sh"
 fi
 
-if [[ -z "$SPARK_HOME" ]]
-then
-  bin=`dirname "$0"`
-  # many hadoop installs are in dir/{spark,hive,hadoop,..}
-  if test -e $bin/../../spark; then 
-    sparkHome=$(readlink -f $bin/../../spark)
-    if [[ -d $sparkHome ]]
-    then
-      export SPARK_HOME=$sparkHome
-    fi
-  fi
-fi
+#if [[ -z "$SPARK_HOME" ]]
+#then
+#  bin=`dirname "$0"`
+#  # many hadoop installs are in dir/{spark,hive,hadoop,..}
+#  if test -e $bin/../../spark; then 
+#    sparkHome=$(readlink -f $bin/../../spark)
+#    if [[ -d $sparkHome ]]
+#    then
+#      export SPARK_HOME=$sparkHome
+#    fi
+#  fi
+#fi
 
 CLASSPATH="${HIVE_CONF_DIR}"
 
@@ -166,40 +166,40 @@ else
 fi
 
 # supress the HADOOP_HOME warnings in 1.x.x
-export HADOOP_HOME_WARN_SUPPRESS=true 
+#export HADOOP_HOME_WARN_SUPPRESS=true 
 
 # to make sure log4j2.x and jline jars are loaded ahead of the jars pulled by hadoop
-export HADOOP_USER_CLASSPATH_FIRST=true
+#export HADOOP_USER_CLASSPATH_FIRST=true
 
 # pass classpath to hadoop
-if [ "$HADOOP_CLASSPATH" != "" ]; then
-  export HADOOP_CLASSPATH="${CLASSPATH}:${HADOOP_CLASSPATH}"
-else
-  export HADOOP_CLASSPATH="$CLASSPATH"
-fi
+#if [ "$HADOOP_CLASSPATH" != "" ]; then
+#  export HADOOP_CLASSPATH="${CLASSPATH}:${HADOOP_CLASSPATH}"
+#else
+#  export HADOOP_CLASSPATH="$CLASSPATH"
+#fi
 
 # also pass hive classpath to hadoop
-if [ "$HIVE_CLASSPATH" != "" ]; then
-  export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:${HIVE_CLASSPATH}";
-fi
+#if [ "$HIVE_CLASSPATH" != "" ]; then
+#  export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:${HIVE_CLASSPATH}";
+#fi
 
 # check for hadoop in the path
-HADOOP_IN_PATH=`which hadoop 2>/dev/null`
-if [ -f ${HADOOP_IN_PATH} ]; then
-  HADOOP_DIR=`dirname "$HADOOP_IN_PATH"`/..
-fi
+#HADOOP_IN_PATH=`which hadoop 2>/dev/null`
+#if [ -f ${HADOOP_IN_PATH} ]; then
+#  HADOOP_DIR=`dirname "$HADOOP_IN_PATH"`/..
+#fi
 # HADOOP_HOME env variable overrides hadoop in the path
-HADOOP_HOME=${HADOOP_HOME:-${HADOOP_PREFIX:-$HADOOP_DIR}}
-if [ "$HADOOP_HOME" == "" ]; then
-  echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
-  exit 4;
-fi
+#HADOOP_HOME=${HADOOP_HOME:-${HADOOP_PREFIX:-$HADOOP_DIR}}
+#if [ "$HADOOP_HOME" == "" ]; then
+#  echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
+#  exit 4;
+#fi
 
-HADOOP=$HADOOP_HOME/bin/hadoop
-if [ ! -f ${HADOOP} ]; then
-  echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
-  exit 4;
-fi
+#HADOOP=$HADOOP_HOME/bin/hadoop
+#if [ ! -f ${HADOOP} ]; then
+#  echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
+#  exit 4;
+#fi
 
 if [ ! -d ${TMP_USER_DIR} ]; then
   mkdir -p ${TMP_USER_DIR} 2> /dev/null
@@ -216,31 +216,31 @@ if [ "${STDERR}" != "/dev/null" ] && [ ! -f ${STDERR} ]; then
 fi
 
 # Make sure we're using a compatible version of Hadoop
-if [ "x$HADOOP_VERSION" == "x" ]; then
-    HADOOP_VERSION=$($HADOOP version 2>> ${STDERR} | awk -F"\t" '/Hadoop/ {print $0}' | cut -d' ' -f 2);
-fi
+#if [ "x$HADOOP_VERSION" == "x" ]; then
+#    HADOOP_VERSION=$($HADOOP version 2>> ${STDERR} | awk -F"\t" '/Hadoop/ {print $0}' | cut -d' ' -f 2);
+#fi
 
 # Save the regex to a var to workaround quoting incompatabilities
 # between Bash 3.1 and 3.2
-hadoop_version_re="^([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))?.*$"
+#hadoop_version_re="^([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))?.*$"
 
-if [[ "$HADOOP_VERSION" =~ $hadoop_version_re ]]; then
-    hadoop_major_ver=${BASH_REMATCH[1]}
-    hadoop_minor_ver=${BASH_REMATCH[2]}
-    hadoop_patch_ver=${BASH_REMATCH[4]}
-else
-    echo "Unable to determine Hadoop version information."
-    echo "'hadoop version' returned:"
-    echo `$HADOOP version`
-    exit 5
-fi
+#if [[ "$HADOOP_VERSION" =~ $hadoop_version_re ]]; then
+#    hadoop_major_ver=${BASH_REMATCH[1]}
+#    hadoop_minor_ver=${BASH_REMATCH[2]}
+#    hadoop_patch_ver=${BASH_REMATCH[4]}
+#else
+#    echo "Unable to determine Hadoop version information."
+#    echo "'hadoop version' returned:"
+#    echo `$HADOOP version`
+#    exit 5
+#fi
 
-if [ "$hadoop_major_ver" -lt "1" -a  "$hadoop_minor_ver$hadoop_patch_ver" -lt "201" ]; then
-    echo "Hive requires Hadoop 0.20.x (x >= 1)."
-    echo "'hadoop version' returned:"
-    echo `$HADOOP version`
-    exit 6
-fi
+#if [ "$hadoop_major_ver" -lt "1" -a  "$hadoop_minor_ver$hadoop_patch_ver" -lt "201" ]; then
+#    echo "Hive requires Hadoop 0.20.x (x >= 1)."
+#    echo "'hadoop version' returned:"
+#    echo `$HADOOP version`
+#    exit 6
+#fi
 
 # HBase detection. Need bin/hbase and a conf dir for building classpath entries.
 # Start with BigTop defaults for HBASE_HOME and HBASE_CONF_DIR.
@@ -252,9 +252,9 @@ if [[ ! -d $HBASE_CONF_DIR ]] ; then
 fi
 
 # perhaps we've located the HBase config. if so, include it on classpath.
-if [[ -d $HBASE_CONF_DIR ]] ; then
-  export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:${HBASE_CONF_DIR}"
-fi
+#if [[ -d $HBASE_CONF_DIR ]] ; then
+#  export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:${HBASE_CONF_DIR}"
+#fi
 
 # look for the hbase script. First check HBASE_HOME and then ask PATH.
 if [[ -e $HBASE_HOME/bin/hbase ]] ; then
@@ -263,17 +263,17 @@ fi
 HBASE_BIN=${HBASE_BIN:-"$(which hbase)"}
 
 # perhaps we've located HBase. If so, include its details on the classpath
-if [[ -n $HBASE_BIN ]] ; then
-  # exclude ZK, PB, and Guava (See HIVE-2055)
-  # depends on HBASE-8438 (hbase-0.94.14+, hbase-0.96.1+) for `hbase mapredcp` command
-  for x in $($HBASE_BIN mapredcp 2>> ${STDERR} | tr ':' '\n') ; do
-    if [[ $x == *zookeeper* || $x == *protobuf-java* || $x == *guava* ]] ; then
-      continue
-    fi
-    # TODO: should these should be added to AUX_PARAM as well?
-    export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:${x}"
-  done
-fi
+#if [[ -n $HBASE_BIN ]] ; then
+#  # exclude ZK, PB, and Guava (See HIVE-2055)
+#  # depends on HBASE-8438 (hbase-0.94.14+, hbase-0.96.1+) for `hbase mapredcp` command
+#  for x in $($HBASE_BIN mapredcp 2>> ${STDERR} | tr ':' '\n') ; do
+#    if [[ $x == *zookeeper* || $x == *protobuf-java* || $x == *guava* ]] ; then
+#      continue
+#    fi
+#    # TODO: should these should be added to AUX_PARAM as well?
+#    export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:${x}"
+#  done
+#fi
 
 if [ "${AUX_PARAM}" != "" ]; then
   if [[ "$SERVICE" != beeline ]]; then
@@ -296,9 +296,9 @@ if [ "$DEBUG" ]; then
   if [ "$HELP" ]; then
     debug_help
     exit 0
-  else
-    get_debug_params "$DEBUG"
-    export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS $HIVE_MAIN_CLIENT_DEBUG_OPTS"
+#  else
+#    get_debug_params "$DEBUG"
+#    export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS $HIVE_MAIN_CLIENT_DEBUG_OPTS"
   fi
 fi
 
@@ -309,14 +309,14 @@ for j in $SERVICE_LIST ; do
   fi
 done
 
-# to initialize logging for all services
-export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Dlog4j.configurationFile=hive-log4j2.properties "
+## to initialize logging for all services
+#export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Dlog4j.configurationFile=hive-log4j2.properties "
 
-if [ -f "${HIVE_CONF_DIR}/parquet-logging.properties" ]; then
-  export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Djava.util.logging.config.file=${HIVE_CONF_DIR}/parquet-logging.properties "
-else
-  export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Dlog4j.configurationFile=hive-log4j2.properties -Djava.util.logging.config.file=$bin/../conf/parquet-logging.properties "
-fi
+#if [ -f "${HIVE_CONF_DIR}/parquet-logging.properties" ]; then
+#  export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Djava.util.logging.config.file=${HIVE_CONF_DIR}/parquet-logging.properties "
+#else
+#  export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Dlog4j.configurationFile=hive-log4j2.properties -Djava.util.logging.config.file=$bin/../conf/parquet-logging.properties "
+#fi
 
 if [ "$TORUN" = "" ] ; then
   echo "Service $SERVICE not found"
